name: Lint and build container images for testing

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'sample/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'sample/**'
  workflow_dispatch:

jobs:
  build-container-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./postgresql${{ matrix.version }}/Dockerfile

      - name: Build container images
        run: docker build -t "bitnami-postgresql-pgvector:${{ matrix.version }}" ./postgresql${{ matrix.version }}/

      - name: Check container images
        run: docker image ls
